"""minor fix

Revision ID: 179efdd3ba90
Revises: ce1dc4b4352f
Create Date: 2024-06-02 21:10:02.606911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179efdd3ba90'
down_revision: Union[str, None] = 'ce1dc4b4352f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('rooms', 'discription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('discription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('rooms', 'description')
    # ### end Alembic commands ###
